 stages:
  - build_image
  - push_image
before_script:
#效验docker镜像库
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
###########################sppf-service-account-server#########################
 - cd sppf-service/sppf-service-account-server
  - mvn clean package -Dmaven.test.skip=true
  - mv Dockerfile target/
  - cd target/
build_image:
  stage: build_image
  script:
  - docker build -t "$CI_REGISTRY/$CI_PROJECT3:$CI_COMMIT_REF_SLUG" .
push_image:
  stage: push_image
  script:
  - docker push "$CI_REGISTRY/$CI_PROJECT3:$CI_COMMIT_REF_SLUG"
  - docker rmi "$CI_REGISTRY/$CI_PROJECT3:$CI_COMMIT_REF_SLUG"
  - cd ../../
############################sppf-service-versatile-server#######################
#  - cd sppf-service/sppf-service-versatile-server
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT1:$CI_COMMIT_REF_SLUG" .
#  - cd ../../
# 
#push_image:
#  stage: push_image
#  script:
#  - docker push "$CI_REGISTRY/$CI_PROJECT1:$CI_COMMIT_REF_SLUG"
#  - docker rmi "$CI_REGISTRY/$CI_PROJECT1:$CI_COMMIT_REF_SLUG"
########################config-server##########################################
#  - cd config-server/
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT4:$CI_COMMIT_REF_SLUG" .
#push_image:
#  stage: push_image
#  script:
#    - docker push "$CI_REGISTRY/$CI_PROJECT4:$CI_COMMIT_REF_SLUG"
#    - docker rmi "$CI_REGISTRY/$CI_PROJECT4:$CI_COMMIT_REF_SLUG"
#    - cd ../
#######################eureka-server#########################################
#  - cd eureka-server/
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT5:$CI_COMMIT_REF_SLUG" .
#push_image:
#  stage: push_image
#  script:
#  - docker push "$CI_REGISTRY/$CI_PROJECT5:$CI_COMMIT_REF_SLUG"
#  - docker rmi "$CI_REGISTRY/$CI_PROJECT5:$CI_COMMIT_REF_SLUG"
#  - cd ../
################################sppf-service-parking-server##################
#  - cd sppf-service/sppf-service-parking-server/
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT6:$CI_COMMIT_REF_SLUG" .
#push_image:
#  stage: push_image
#  script:
#  - docker push "$CI_REGISTRY/$CI_PROJECT6:$CI_COMMIT_REF_SLUG"
#  - docker rmi "$CI_REGISTRY/$CI_PROJECT6:$CI_COMMIT_REF_SLUG"
#  - cd ../../
#################################sppf-service-user-server###################
#  - cd sppf-service/sppf-service-user-server/
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT7:$CI_COMMIT_REF_SLUG" .
#push_image:
#  stage: push_image
#  script:
#  - docker push "$CI_REGISTRY/$CI_PROJECT7:$CI_COMMIT_REF_SLUG"
#  - docker rmi "$CI_REGISTRY/$CI_PROJECT7:$CI_COMMIT_REF_SLUG"
#  - cd ../../
###################################sppf-service-station-service############
#  - cd sppf-service/sppf-service-station-service/
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT8:$CI_COMMIT_REF_SLUG" .
#push_image:
#  stage: push_image
#  script:
#  - docker push "$CI_REGISTRY/$CI_PROJECT8:$CI_COMMIT_REF_SLUG"
#  - docker rmi "$CI_REGISTRY/$CI_PROJECT8:$CI_COMMIT_REF_SLUG"
#  - cd ../../
##################################sppf-service-order-server##############
#  - cd sppf-service/sppf-service-order-server/
#  - mvn clean package -Dmaven.test.skip=true
#  - mv Dockerfile target/
#  - cd target/
#build_image:
#  stage: build_image
#  script:
#  - docker build -t "$CI_REGISTRY/$CI_PROJECT9:$CI_COMMIT_REF_SLUG" .
#  - cd ../../
#push_image:
#  stage: push_image
#  script:
#  - docker push "$CI_REGISTRY/$CI_PROJECT9:$CI_COMMIT_REF_SLUG"
#  - docker rmi "$CI_REGISTRY/$CI_PROJECT9:$CI_COMMIT_REF_SLUG"


