stages:
  - build_image
  - push_image
 
before_script:
  - cd sppf-service/sppf-service-versatile-server/
  - mvn install -Dmaven.test.skip=true
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 
build_image:
  stage: build_image
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
 
push_image:
  stage: push_image
  script:
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    #- docker rmi "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
