stages:
  - build_image
  - push_image
before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

############################sppf-service-versatile-server#######################
 - cd sppf-service/sppf-service-versatile-server
  - mvn clean package -Dmaven.test.skip=true
- mv Dockerfile target/
 - cd target/
build_image:
  stage: build_image
  script:
  - docker build -t "$CI_REGISTRY/$CI_PROJECT1:$CI_COMMIT_REF_SLUG" .
 
push_image:
  stage: push_image
  script:
  - docker push "$CI_REGISTRY/$CI_PROJECT1:$CI_COMMIT_REF_SLUG"
  - docker rmi "$CI_REGISTRY/$CI_PROJECT1:$CI_COMMIT_REF_SLUG"



