socket:
  io:
    host: 127.0.0.1
    port: 9001
    max-frame-payload-length: 11111
    max-http-content-length: 111111
    boss-count: 1
    work-count: 100
    allow-custom-requests: true
    upgrade-timeout: 1000000
    ping-timeout: 6000000
    ping-interval: 25000
